version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./app/infra/qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - vietnam-law-network
    restart: unless-stopped

  neo4j:
    image: neo4j:5.15-community
    ports:
      - "7474:7474"  # HTTP Browser
      - "7687:7687"  # Bolt Protocol
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    volumes:
      - ./app/infra/neo4j/neo4j_data:/data
      - ./app/infra/neo4j/neo4j_logs:/logs
      - ./app/infra/neo4j/neo4j_import:/var/lib/neo4j/import
      - ..app/infra/neo4j/neo4j_plugins:/plugins
    networks:
      - vietnam-law-network
    restart: unless-stopped

networks:
  vietnam-law-network:
    driver: bridge
