name: CI

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd app/backend
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 app/backend --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test imports
      run: |
        cd app/backend
        python -c "import core.config; print('✅ Config import successful')"
        python -c "import main; print('✅ FastAPI app validation passed')"
